lab_1/urls.py
from django.urls import path
from .views import index, friend_list

urlpatterns = [
    path('', index, name='index'),
    path('friends', friend_list),
]

lab_2/urls.py
from django.urls import path
from .views import index, xml, json

urlpatterns = [
    path('', index),
    path('xml', xml),
    path('json', json),
]

lab_3/urls.py
from django.urls import path
from .views import index, add_friend

# Used for POST redirect
# Source: https://stackoverflow.com/a/52902655
app_name = "lab_3"

urlpatterns = [
    path('', index, name='index'),
    path('add', add_friend, name='add_friend'),
]

lab_4/urls.py
from django.urls import path
from .views import index, add_note, note_list

# Used for POST redirect
# Source: https://stackoverflow.com/a/52902655
app_name = "lab_4"

urlpatterns = [
    path('', index, name='index'),
    path('add-note', add_note, name='add_note'),
    path('note-list', note_list, name='note_list'),
]

lab_5/urls.py
from django.urls import path
from .views import index

# Used for POST redirect
# Source: https://stackoverflow.com/a/52902655
app_name = "lab_5"

urlpatterns = [
    path('', index, name='index'),
]

praktikum/urls.py
from django.urls import path, re_path, include
from django.contrib import admin
from lab_1.views import index as index_lab1

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lab-1/', include('lab_1.urls')),
    path('lab-2/', include('lab_2.urls')),
    path('lab-3/', include('lab_3.urls')),
    path('lab-4/', include('lab_4.urls')),
    path('lab-5/', include('lab_5.urls')),
    re_path(r'^$', index_lab1, name='index')
]

lab_1/models.py
from django.db import models

class Friend(models.Model):
    name = models.CharField(max_length=30)
    npm = models.PositiveIntegerField()
    dob = models.DateField(max_length=8)

lab_2/models.py
from django.db import models

# Reference: https://docs.djangoproject.com/en/3.2/ref/models/fields/

class Note(models.Model):
    person_to = models.TextField()
    person_from = models.TextField()
    title = models.TextField()
    message = models.TextField()

lab_3/models.py
from django.db import models

# Create your models here.

lab_4/models.py
from django.db import models

# Create your models here.

lab_5/models.py
from django.db import models

# Create your models here.

lab_3/forms.py
from django.forms import ModelForm, DateInput, widgets
from lab_1.models import Friend

# Define date input for date of birth
# Source: https://www.youtube.com/watch?v=I2-JYxnSiB0
class InputDOB(DateInput):
    input_type = 'date'

class FriendForm(ModelForm):
    class Meta:
        model = Friend
        fields = ['name', 'npm', 'dob']
        # fields = "__all__" (ALTERNATIVE from GeeksforGeeks)
        widgets = {'dob': InputDOB()}

lab_4/forms.py
from typing import Text
from django.forms import ModelForm, Textarea, TextInput
from lab_2.models import Note

# Define widgets
class InputText(TextInput):
    input_type = 'text'

class InputMessage(Textarea):
    input_type = 'text'

class NoteForm(ModelForm):
    class Meta:
        model = Note
        fields = ['person_to', 'person_from', 'title', 'message']
        widgets = {'person_to': InputText(), 'person_from': InputText(), 'title': InputText(), 'message': InputMessage()}

lab_1/views.py
from django.shortcuts import render
from datetime import datetime, date
from .models import Friend

mhs_name = "Muhammad Athallah"
curr_year = int(datetime.now().strftime("%Y"))
birth_date = date(2001, 6, 16)
npm = 2006527481


def index(request):
    response = {'name': mhs_name,
                'age': calculate_age(birth_date.year),
                'npm': npm}
    return render(request, 'index_lab1.html', response)


def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0


def friend_list(request):
    friends = Friend.objects.all()
    response = {'friends': friends}
    return render(request, 'friend_list_lab1.html', response)

lab_2/views.py
from django.shortcuts import render
from django.http.response import HttpResponse
from django.core import serializers
from .models import Note

def index(request):
    notes = Note.objects.all()
    response = {'notes': notes}
    return render(request, 'lab2.html', response)

def xml(request):
    notes = Note.objects.all()
    data = serializers.serialize('xml', notes)
    return HttpResponse(data, content_type="application/xml")

def json(request):
    notes = Note.objects.all()
    data = serializers.serialize('json', notes)
    return HttpResponse(data, content_type="application/json")

lab_3/views.py
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from lab_1.models import Friend
from .forms import FriendForm

@login_required(login_url='/admin/login/')
def index(request):
    # Add order_by to show ascending list by name
    friends = Friend.objects.all().order_by('name')
    response = {'friends': friends}
    return render(request, 'lab3_index.html', response)

@login_required(login_url='/admin/login/')
def add_friend(request):
    # A context is a variable name -> variable value mapping that is passed to a template.
    # Context processors let you specify a number of variables that get set in each context automatically
    # without you having to specify the variables in each render() call.
    # Source: https://stackoverflow.com/questions/20957388/what-is-a-context-in-django
    context = {}
  
    # create object of form
    form = FriendForm(request.POST or None)

    # check if form data is valid (prevent from SQL injection, too)
    if form.is_valid() and request.method == 'POST':
        # save the form data to the model
        form.save()
        # return to index after saving data (POST Redirect)
        return HttpResponseRedirect(reverse('lab_3:index'))
    
    context['form']= form
    return render(request, "lab3_form.html", context)

lab_4/views.py
from django.shortcuts import render
from django.http.response import HttpResponseRedirect
from django.urls import reverse
from lab_2.models import Note
from .forms import NoteForm

def index(request):
    notes = Note.objects.all()
    response = {'notes': notes}
    return render(request, 'lab4_index.html', response)

def add_note(request):
    # create object of form
    form = NoteForm(request.POST or None)

    # check if form data is valid (prevent from SQL injection, too)
    if form.is_valid() and request.method == 'POST':
        # save the form data to the model
        form.save()
        # return to index after saving data (POST Redirect)
        return HttpResponseRedirect(reverse('lab_4:index'))
    
    context = {'form': form}
    return render(request, "lab4_form.html", context)

def note_list(request):
    notes = Note.objects.all()
    response = {'notes': notes}
    return render(request, 'lab4_note_list.html', response)

lab_5/views.py
from django.core import serializers
from django.http.response import HttpResponse
from django.shortcuts import render
from lab_2.models import Note
import json

def index(request):
    notes = Note.objects.all()
    response = {'notes': notes}
    return render(request, 'lab5_index.html', response)

def get_note(request, id):
    note = Note.objects.get(id = id)
    data = serializers.serialize('json', [note, ])

    struct = json.loads(data)
    data = json.dumps(struct[0])
    return HttpResponse(data, content_type='application/json')

lab_1/templates/friend_list_lab1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Friend List</title>
  </head>
  <body>
    <table>
      <tr>
        <th>Name</th>
        <th>NPM</th>
        <th>DOB</th>
      </tr>
      {% for friend in friends %}
      <tr>
        <td>{{ friend.name }}</td>
        <td>{{ friend.npm }}</td>
        <td>{{ friend.dob }}</td>
      </tr>
      {% endfor %}
    </table>
  </body>
</html>

lab_1/templates/index_lab1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{{ name }}</title>
  </head>
  <body>
    <h1>Hello my name is {{ name }}</h1>
    <article>NPM : {{ npm }}</article>
    <article>I am {{ age }} years old</article>
  </body>
</html>

lab_2/templates/lab2.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Notes</title>
  </head>
  <body>
    <table border="1">
      <tr>
        <th>To</th>
        <th>From</th>
        <th>Title</th>
        <th>Message</th>
      </tr>
      {% for note in notes %}
      <tr>
        <td>{{ note.person_to }}</td>
        <td>{{ note.person_from }}</td>
        <td>{{ note.title }}</td>
        <td>{{ note.message }}</td>
      </tr>
      {% endfor %}
    </table>
  </body>
</html>

lab_3/templates/lab3_form.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Form - Add Friend</title>
  </head>
  <body>
   <h2>Add Friend to Friend List</h2>
    <div>
      <div>
        <form method="POST" action="">
          {%csrf_token%}
          <div role="alert">
            <p>Nama: {{ form.name }}</p>
            <p>NPM: {{ form.npm }}</p>
            <p>Tanggal Lahir: {{ form.dob }}</p>
          </div>
          <div>
            <input type="submit" value="Submit"/>
          </div>
        </form>
      </div>
    </div>
  </body>
</html>

lab_3/templates/lab3_index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Friend List</title>
  </head>
  <body>
    <h2>Friend List</h2>
    <table border="1">
      <tr>
        <th>Name</th>
        <th>NPM</th>
        <th>DOB</th>
      </tr>
      {% for friend in friends %}
      <tr>
        <td>{{ friend.name }}</td>
        <td>{{ friend.npm }}</td>
        <td>{{ friend.dob }}</td>
      </tr>
      {% endfor %}
    </table>
    <p>If you have privilege to add friend to the friend list, you can add friend by clicking the button under this text.</p>
    <button><a href="add">Add Friend</a></button>
  </body>
</html>

lab_4/templates/lab4_form.html
<!--  Load static files -->
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <!--  This template has been downloaded from bootdey.com @bootdey on twitter -->
    <!-- Link: https://www.bootdey.com/snippets/view/notes-dashboard -->
    <!--  All snippets are MIT license http://bootdey.com/license -->
    <title>Notes - Card View</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" rel="stylesheet">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<div class="page-content container note-has-grid">
    <ul class="nav nav-pills p-3 bg-white mb-3 rounded-pill align-items-center">
        <li class="nav-item">
            <a href="{% url 'lab_4:index' %}" class="nav-link rounded-pill note-link d-flex align-items-center px-2 px-md-3 mr-0 mr-md-2 active" id="all-category">
                <span class="d-none d-md-block">Table View</span>
            </a>
        </li>
        <li class="nav-item">
            <a href="{% url 'lab_4:note_list' %}" class="nav-link rounded-pill note-link d-flex align-items-center px-2 px-md-3 mr-0 mr-md-2 active" id="all-category">
                <span class="d-none d-md-block">Card View</span>
            </a>
        </li>
        <li class="nav-item ml-auto">
            <a href="{% url 'lab_4:add_note' %}" class="nav-link btn-primary rounded-pill d-flex align-items-center px-3" id="add-notes"> <span class="d-none d-md-block font-14">Add Notes</span></a>
        </li>
    </ul>
    <div class="tab-content bg-transparent">
        <div id="note-full-container" class="note-has-grid row">
            <div class="col-xl-12 single-note-item all-category">
                <div class="card card-body">
                    <form method="POST" action="">
                        {%csrf_token%}
                        <div class="row">
                            <div class="col-md-12 mb-3">
                                <div class="note-person-from">
                                    <label>From</label>
                                    <br>
                                    {{ form.person_from }}
                                </div>
                            </div>

                            <div class="col-md-12 mb-3">
                                <div class="note-person-to">
                                    <label>To</label>
                                    <br>
                                    {{ form.person_to }}
                                </div>
                            </div>

                            <div class="col-md-12 mb-3">
                                <div class="note-title">
                                    <label>Title</label>
                                    <br>
                                    {{ form.title }}
                                </div>
                            </div>

                            <div class="col-md-12 mb-3">
                                <div class="note-message">
                                    <label>Message</label>
                                    <br>
                                    {{ form.message }}
                                </div>
                            </div>
                        </div>
                        <div class="form-footer">
                            <input type="submit" class="btn btn-info" value="Add"/>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<link href="{% static 'css/form_style.css' %}" rel="stylesheet" type="text/css">

</body>
</html>

lab_4/templates/lab4_index.html
<!--  Load static files -->
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <!--  This template has been downloaded from bootdey.com @bootdey on twitter -->
    <!-- Link: https://www.bootdey.com/snippets/view/notes-dashboard -->
    <!--  All snippets are MIT license http://bootdey.com/license -->
    <title>Notes - Card View</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" rel="stylesheet">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<div class="page-content container note-has-grid">
    <ul class="nav nav-pills p-3 bg-white mb-3 rounded-pill align-items-center">
        <li class="nav-item">
            <a href="{% url 'lab_4:index' %}" class="nav-link rounded-pill note-link d-flex align-items-center px-2 px-md-3 mr-0 mr-md-2 active" id="all-category">
                <span class="d-none d-md-block">Table View</span>
            </a>
        </li>
        <li class="nav-item">
            <a href="{% url 'lab_4:note_list' %}" class="nav-link rounded-pill note-link d-flex align-items-center px-2 px-md-3 mr-0 mr-md-2 active" id="all-category">
                <span class="d-none d-md-block">Card View</span>
            </a>
        </li>
        <li class="nav-item ml-auto">
            <a href="{% url 'lab_4:add_note' %}" class="nav-link btn-primary rounded-pill d-flex align-items-center px-3" id="add-notes"> <span class="d-none d-md-block font-14">Add Notes</span></a>
        </li>
    </ul>
    <div class="tab-content bg-transparent">
        <div id="note-full-container" class="note-has-grid row">
            <div class="col-xl-12 single-note-item all-category">
                <div class="card card-body">
                  <table>
                    <tr>
                      <th class="note-table-header text-truncate mb-0">To</th>
                      <th class="note-table-header text-truncate mb-0">From</th>
                      <th class="note-table-header text-truncate mb-0">Title</th>
                      <th class="note-table-header text-truncate mb-0">Message</th>
                    </tr>
                    {% for note in notes %}
                    <tr>
                      <td class="note-table-data text-muted">{{ note.person_to }}</td>
                      <td class="note-table-data text-muted">{{ note.person_from }}</td>
                      <td class="note-table-data text-muted">{{ note.title }}</td>
                      <td class="note-table-data text-muted">{{ note.message }}</td>
                    </tr>
                    {% endfor %}
                  </table>
                </div>
            </div>
        </div>
    </div>
</div>

<link href="{% static 'css/table_style.css' %}" rel="stylesheet" type="text/css">

</body>
</html>

lab_4/templates/lab4_note_list.html
<!--  Load static files -->
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <!--  This template has been downloaded from bootdey.com @bootdey on twitter -->
    <!-- Link: https://www.bootdey.com/snippets/view/notes-dashboard -->
    <!--  All snippets are MIT license http://bootdey.com/license -->
    <title>Notes - Card View</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" rel="stylesheet">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<div class="page-content container note-has-grid">
    <ul class="nav nav-pills p-3 bg-white mb-3 rounded-pill align-items-center">
        <li class="nav-item">
            <a href="{% url 'lab_4:index' %}" class="nav-link rounded-pill note-link d-flex align-items-center px-2 px-md-3 mr-0 mr-md-2 active" id="all-category">
                <span class="d-none d-md-block">Table View</span>
            </a>
        </li>
        <li class="nav-item">
            <a href="{% url 'lab_4:note_list' %}" class="nav-link rounded-pill note-link d-flex align-items-center px-2 px-md-3 mr-0 mr-md-2 active" id="all-category">
                <span class="d-none d-md-block">Card View</span>
            </a>
        </li>
        <li class="nav-item ml-auto">
            <a href="{% url 'lab_4:add_note' %}" class="nav-link btn-primary rounded-pill d-flex align-items-center px-3" id="add-notes"> <span class="d-none d-md-block font-14">Add Notes</span></a>
        </li>
    </ul>
    <div class="tab-content bg-transparent">
        <div id="note-full-container" class="note-has-grid row">
            {% for note in notes %}
            <div class="col-md-4 single-note-item all-category">
                <div class="card card-body">
                    <h4 class="note-title text-truncate w-75 mb-0">{{ note.title }}</h4> 
                    <p class="note-person text-muted">To: {{ note.person_to }}</p>
                    <p class="note-person text-muted">From: {{ note.person_from }}</p>
                    <hr>
                    <div class="note-content">
                        <p class="note-inner-content text-muted">{{ note.message }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

<link href="{% static 'css/card_style.css' %}" rel="stylesheet" type="text/css">

</body>
</html>

lab_5/templates/add_modal.html
<!-- Modal Add notes -->
<div class="modal fade" id="addnotesmodal" tabindex="-1" role="dialog" aria-labelledby="addnotesmodalTitle" style="display: none;" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content border-0">
            <div class="modal-header bg-info text-white">
                <h5 class="modal-title text-white">Add Notes</h5>
                <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="notes-box">
                    <div class="notes-content">
                        <form action="javascript:void(0);" id="addnotesmodalTitle">
                            <div class="row">
                                <div class="col-md-12 mb-3">
                                    <div class="note-title">
                                        <label>Note Title</label>
                                        <input type="text" id="note-has-title" class="form-control" minlength="25" placeholder="Title" />
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="note-description">
                                        <label>Note Description</label>
                                        <textarea id="note-has-description" class="form-control" minlength="60" placeholder="Description" rows="3"></textarea>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button id="btn-n-save" class="float-left btn btn-success" style="display: none;">Save</button>
                <button class="btn btn-danger" data-dismiss="modal">Discard</button>
                <button id="btn-n-add" class="btn btn-info" disabled="disabled">Add</button>
            </div>
        </div>
    </div>
</div>

lab_5/templates/lab5_index.html
<!--  Load static files -->
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <!--  This template has been downloaded from bootdey.com @bootdey on twitter -->
    <!--  Link: https://www.bootdey.com/snippets/view/notes-dashboard -->
    <!--  All snippets are MIT license http://bootdey.com/license -->
    <title>Notes - Dashboard</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--  Import jQuery -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <!--  Import Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.bundle.min.js"></script>
</head>

<body>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <div class="page-content container note-has-grid">
        <ul class="nav nav-pills p-3 bg-white mb-3 rounded-pill align-items-center">
            <li class="nav-item">
                <a href="javascript:void(0)"
                    class="nav-link rounded-pill note-link d-flex align-items-center px-2 px-md-3 mr-0 mr-md-2 active"
                    id="all-category">
                    <span class="d-none d-md-block">All Notes</span>
                </a>
            </li>
            <li class="nav-item ml-auto">
                <a href="javascript:void(0)" class="nav-link btn-primary rounded-pill d-flex align-items-center px-3"
                    id="add-notes"> <span class="d-none d-md-block font-14">Add Notes</span></a>
            </li>
        </ul>
        <div class="tab-content bg-transparent">
            <div id="note-full-container" class="note-has-grid row">
                <div class="col-xl-12 single-note-item all-category">
                    <div class="card card-body">
                        <table>
                            <thead>
                                <tr>
                                    <th class="note-table-header text-truncate mb-0">To</th>
                                    <th class="note-table-header text-truncate mb-0">From</th>
                                    <th class="note-table-header text-truncate mb-0">Title</th>
                                    <!-- <th class="note-table-header text-truncate mb-0">Message</th> -->
                                    <th class="note-table-header text-truncate mb-0">Actions</th>
                                </tr>
                            </thead>
                            <tbody class="table-body" id="tablebody"></tbody>
                            <!-- Script in view_note.js -->
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <!-- Add modal files -->
        {% include 'add_modal.html' %}
        {% include 'view_modal.html' %}
    </div>

    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">

    <script type="text/javascript" src="{% static 'js/view_note.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/function.js' %}"></script>
</body>

</html>

lab_5/templates/view_modal.html
<!-- Modal view notes -->
<div class="modal fade" id="viewnotemodal" tabindex="-1" role="dialog" aria-labelledby="viewnotemodalTitle" style="display: none;" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content border-0">
            <div class="modal-header bg-info text-white">
                <h5 class="modal-title text-white">Note Details</h5>
                <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="notes-box">
                    <div class="notes-content">
                        <form action="javascript:void(0);" id="viewnotemodalTitle">
                            <div class="row">
                                <div class="col-md-12 mb-3">
                                    <div class="note-title">
                                        <label>Note Title</label>
                                        <input type="text" id="note-has-title" class="form-control" minlength="25" placeholder="Title" />
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="note-description">
                                        <label>Note Description</label>
                                        <textarea id="note-has-description" class="form-control" minlength="60" placeholder="Description" rows="3"></textarea>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>